baseURL = 'https://scgeiger.github.io/'
languageCode = 'en-us'
title = 'NN Lab: Introduction to AWS Security Guidelines'
theme = "hugo-theme-techdoc"


[params]
    # Source Code repository section
#    description = "put your description"
#    github_repository = "https://github.com/scgeiger/awswiki"
#    version = "0.9.9"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
#    github_doc_repository = "https://github.com/thingsym/hugo-theme-techdoc"
#    github_doc_repository_path = ""

    # Theme settings section
    # Theme color
    # See color value reference https://developer.mozilla.org/en-US/docs/Web/CSS/color
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
        identifier = 'home'
        pre = "<i class='fa fa-heart'></i>&nbsp;"

    [[menu.main]]
        name = "Twitter"
        url = "https://twitter.com/thingsym"
        weight = 2
        identifier = 'twitter'
        pre = "<b>pre!</b> "
        post = " <b>post!</b>"
        [menu.main.params]
          class = 'twitter-menu-item'
